# Generated by Django 5.2.9 on 2026-07-14 06:19

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_publicprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('public_display_name'), condition=models.Q(('public_display_name', ''), _negated=True), name='unique_public_display_name_ci'),
        ),
    ]
