"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root is one level above backend
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables from BASE_DIR/.env explicitly to avoid CWD issues in production
load_dotenv(BASE_DIR / ".env")


def _env_str(name: str, default: str = "") -> str:
    """Read environment values robustly as strings."""
    value = os.getenv(name, default)
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ov1io#b(%s+zc#ue30exe(t(sa3d7xf*i4biy7zh*yx95pzitd'
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, explicitly set DEBUG=False via environment variable
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Environment selector used for security-sensitive development overrides.
DJANGO_ENV = _env_str('DJANGO_ENV', 'production').lower()

# Parse ALLOWED_HOSTS from environment variable or use sensible development defaults
_allowed_hosts_str = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
)
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_str.split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'farm',
    'accounts',
]

# Debug Toolbar nur in Entwicklung aktivieren
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    # Debug Toolbar Middleware nur in Entwicklung aktivieren
    *(['debug_toolbar.middleware.DebugToolbarMiddleware'] if DEBUG else []),
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Debug Toolbar Einstellungen nur in Entwicklung
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite if DB_ENGINE is not set or set to 'sqlite', otherwise use PostgreSQL
db_engine = os.getenv('DB_ENGINE', 'sqlite')

if db_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'farmplanner_db'),
            'USER': os.getenv('DB_USER', 'farmplanner'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'farmplanner'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
if DJANGO_ENV == 'development':
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Media files (user uploads)
# Media files are stored at project root level (next to backend and frontend folders)
# to keep them separate from the application code
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', PROJECT_ROOT / 'media'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend base URL used for links in account emails.
FRONTEND_URL = _env_str('FRONTEND_URL', 'http://localhost:5173/openfarmplanner')

# Email configuration (Uberspace SMTP in production, console backend in local development by default).
EMAIL_BACKEND = _env_str(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = _env_str('EMAIL_HOST', 'mail.uberspace.de')
EMAIL_PORT = int(_env_str('EMAIL_PORT', '587') or '587')
EMAIL_USE_TLS = _env_str('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = _env_str('EMAIL_HOST_USER', 'noreply@zwiebelzopf.at')
EMAIL_HOST_PASSWORD = _env_str('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = _env_str('DEFAULT_FROM_EMAIL', 'OpenFarmPlanner <noreply@zwiebelzopf.at>')

# CORS and CSRF origins are intentionally configured independently via environment variables.
_cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins_str.split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-project-id',
]

_csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_str.split(',') if origin.strip()]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')



# AI enrichment settings
AI_ENRICHMENT_ENABLED = os.getenv('AI_ENRICHMENT_ENABLED', 'True').lower() in ('true', '1', 'yes')
AI_ENRICHMENT_PROVIDER = _env_str('AI_ENRICHMENT_PROVIDER', _env_str('ENRICHMENT_PROVIDER', 'openai_responses'))
OPENAI_API_KEY = _env_str('OPENAI_API_KEY', '')
AI_ENRICHMENT_MODEL = _env_str('AI_ENRICHMENT_MODEL', 'gpt-5')
ENABLE_EXTERNAL_ENRICHMENT = os.getenv('ENABLE_EXTERNAL_ENRICHMENT', 'False').lower() in ('true', '1', 'yes')
AI_ENRICHMENT_TIMEOUT_SECONDS = int(_env_str('AI_ENRICHMENT_TIMEOUT_SECONDS', '180') or '180')
AI_ENRICHMENT_CONNECT_TIMEOUT_SECONDS = float(_env_str('AI_ENRICHMENT_CONNECT_TIMEOUT_SECONDS', '10') or '10')
_ai_read_timeout_raw = _env_str('AI_ENRICHMENT_READ_TIMEOUT_SECONDS', '')
AI_ENRICHMENT_READ_TIMEOUT_SECONDS = float(_ai_read_timeout_raw) if _ai_read_timeout_raw else None
OPENAI_RESPONSES_API_URL = _env_str('OPENAI_RESPONSES_API_URL', 'https://api.openai.com/v1/responses')
AI_ENRICHMENT_FAIL_FAST = os.getenv('AI_ENRICHMENT_FAIL_FAST', 'False' if DEBUG else 'True').lower() in ('true', '1', 'yes')
AI_STARTUP_DIAGNOSTICS = os.getenv('AI_STARTUP_DIAGNOSTICS', 'True').lower() in ('true', '1', 'yes')
