"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root is one level above backend
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables from BASE_DIR/.env explicitly to avoid CWD issues in production
load_dotenv(BASE_DIR / ".env")


def _env_str(name: str, default: str = "") -> str:
    """Read environment values robustly as strings."""
    value = os.getenv(name, default)
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ov1io#b(%s+zc#ue30exe(t(sa3d7xf*i4biy7zh*yx95pzitd'
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, explicitly set DEBUG=False via environment variable
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Environment selector used for security-sensitive development overrides.
DJANGO_ENV = _env_str('DJANGO_ENV', 'production').lower()

# Parse ALLOWED_HOSTS from environment variable or use sensible development defaults
_allowed_hosts_str = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
)
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_str.split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'farm',
    'accounts',
]

# Debug Toolbar nur in Entwicklung aktivieren
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    # Debug Toolbar Middleware nur in Entwicklung aktivieren
    *(['debug_toolbar.middleware.DebugToolbarMiddleware'] if DEBUG else []),
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Debug Toolbar Einstellungen nur in Entwicklung
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite if DB_ENGINE is not set or set to 'sqlite', otherwise use PostgreSQL
db_engine = os.getenv('DB_ENGINE', 'sqlite')

if db_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'farmplanner_db'),
            'USER': os.getenv('DB_USER', 'farmplanner'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'farmplanner'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
if DJANGO_ENV == 'development':
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Localhost uses /static/ by default; production can override via DJANGO_STATIC_URL.
STATIC_URL = _env_str('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (user uploads)
# Media files are stored at project root level (next to backend and frontend folders)
# to keep them separate from the application code
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', PROJECT_ROOT / 'media'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend base URL used for links in account emails.
def _normalize_url_prefix(raw_value: str) -> str:
    trimmed = raw_value.strip()
    if not trimmed or trimmed == '/':
        return ''
    return trimmed.strip('/')


URL_PREFIX = _normalize_url_prefix(_env_str('URL_PREFIX', ''))

_frontend_url_from_env = _env_str('FRONTEND_URL', '')
FRONTEND_URL = _frontend_url_from_env or 'http://localhost:5173'
_public_frontend_url_from_env = _env_str('PUBLIC_FRONTEND_URL', '')
PUBLIC_FRONTEND_URL = _public_frontend_url_from_env or FRONTEND_URL

if not DEBUG:
    if SECRET_KEY == 'django-insecure-ov1io#b(%s+zc#ue30exe(t(sa3d7xf*i4biy7zh*yx95pzitd':
        raise ImproperlyConfigured('SECRET_KEY must be set explicitly when DEBUG is False.')
    parsed_public_frontend_url = urlparse(PUBLIC_FRONTEND_URL)
    if not parsed_public_frontend_url.scheme or not parsed_public_frontend_url.netloc:
        raise ImproperlyConfigured('PUBLIC_FRONTEND_URL must be an absolute URL when DEBUG is False.')
    if (parsed_public_frontend_url.hostname or '').lower() in {'localhost', '127.0.0.1', '::1'}:
        raise ImproperlyConfigured('PUBLIC_FRONTEND_URL must not point to localhost when DEBUG is False.')

PROJECT_INVITATION_EXPIRY_DAYS = int(_env_str('PROJECT_INVITATION_EXPIRY_DAYS', '14') or '14')
AGENT_LOGIN_ENABLED = _env_str('AGENT_LOGIN_ENABLED', 'False').lower() in ('true', '1', 'yes')

# Email configuration (console backend by default in development, SMTP in production).
EMAIL_BACKEND = _env_str('EMAIL_BACKEND', '')
if not EMAIL_BACKEND:
    EMAIL_BACKEND = (
        'django.core.mail.backends.console.EmailBackend'
        if DJANGO_ENV == 'development'
        else 'django.core.mail.backends.smtp.EmailBackend'
    )
EMAIL_HOST = _env_str('EMAIL_HOST', 'mail.uberspace.de')
EMAIL_PORT = int(_env_str('EMAIL_PORT', '587') or '587')
EMAIL_USE_TLS = _env_str('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = _env_str('EMAIL_HOST_USER', 'noreply@zwiebelzopf.at')
EMAIL_HOST_PASSWORD = _env_str('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = _env_str('DEFAULT_FROM_EMAIL', 'OpenFarmPlanner <noreply@zwiebelzopf.at>')
SERVER_EMAIL = _env_str('SERVER_EMAIL', EMAIL_HOST_USER)

# CORS and CSRF origins are intentionally configured independently via environment variables.
_cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins_str.split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-project-id',
]

_csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_str.split(',') if origin.strip()]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _env_str('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = _env_str('CSRF_COOKIE_SAMESITE', 'Lax')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_str('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_SECONDS = int(_env_str('SECURE_HSTS_SECONDS', '31536000') or '31536000')
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_str('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_PRELOAD = _env_str('SECURE_HSTS_PRELOAD', 'True').lower() in ('true', '1', 'yes')
    SECURE_REFERRER_POLICY = _env_str('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
    X_FRAME_OPTIONS = _env_str('X_FRAME_OPTIONS', 'DENY')
    SECURE_CONTENT_TYPE_NOSNIFF = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': _env_str('THROTTLE_AUTH_LOGIN', '10/minute'),
        'auth_register': _env_str('THROTTLE_AUTH_REGISTER', '5/minute'),
        'auth_activation': _env_str('THROTTLE_AUTH_ACTIVATION', '10/minute'),
        'auth_resend_activation': _env_str('THROTTLE_AUTH_RESEND_ACTIVATION', '5/minute'),
        'auth_password_reset_request': _env_str('THROTTLE_AUTH_PASSWORD_RESET_REQUEST', '5/minute'),
        'auth_password_reset_confirm': _env_str('THROTTLE_AUTH_PASSWORD_RESET_CONFIRM', '10/minute'),
        'invitation_accept': _env_str('THROTTLE_INVITATION_ACCEPT', '20/hour'),
        'agent_login_consume': _env_str('THROTTLE_AGENT_LOGIN_CONSUME', '30/hour'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

CSRF_COOKIE_SAMESITE = _env_str('CSRF_COOKIE_SAMESITE', CSRF_COOKIE_SAMESITE)
SESSION_COOKIE_SAMESITE = _env_str('SESSION_COOKIE_SAMESITE', SESSION_COOKIE_SAMESITE)
if DEBUG:
    CSRF_COOKIE_SECURE = _env_str('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
    SESSION_COOKIE_SECURE = _env_str('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')



# AI enrichment settings
AI_ENRICHMENT_ENABLED = os.getenv('AI_ENRICHMENT_ENABLED', 'True').lower() in ('true', '1', 'yes')
AI_ENRICHMENT_PROVIDER = _env_str('AI_ENRICHMENT_PROVIDER', _env_str('ENRICHMENT_PROVIDER', 'openai_responses'))
OPENAI_API_KEY = _env_str('OPENAI_API_KEY', '')
AI_ENRICHMENT_MODEL = _env_str('AI_ENRICHMENT_MODEL', 'gpt-5')
ENABLE_EXTERNAL_ENRICHMENT = os.getenv('ENABLE_EXTERNAL_ENRICHMENT', 'False').lower() in ('true', '1', 'yes')
AI_ENRICHMENT_TIMEOUT_SECONDS = int(_env_str('AI_ENRICHMENT_TIMEOUT_SECONDS', '180') or '180')
AI_ENRICHMENT_CONNECT_TIMEOUT_SECONDS = float(_env_str('AI_ENRICHMENT_CONNECT_TIMEOUT_SECONDS', '10') or '10')
_ai_read_timeout_raw = _env_str('AI_ENRICHMENT_READ_TIMEOUT_SECONDS', '')
AI_ENRICHMENT_READ_TIMEOUT_SECONDS = float(_ai_read_timeout_raw) if _ai_read_timeout_raw else None
OPENAI_RESPONSES_API_URL = _env_str('OPENAI_RESPONSES_API_URL', 'https://api.openai.com/v1/responses')
AI_ENRICHMENT_FAIL_FAST = os.getenv('AI_ENRICHMENT_FAIL_FAST', 'False' if DEBUG else 'True').lower() in ('true', '1', 'yes')
AI_STARTUP_DIAGNOSTICS = os.getenv('AI_STARTUP_DIAGNOSTICS', 'True').lower() in ('true', '1', 'yes')

E2E_TEST_TOKEN = os.getenv('E2E_TEST_TOKEN', '').strip()
