"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from pathlib import Path
from urllib.parse import urlparse

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root is one level above backend
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables from BASE_DIR/.env explicitly to avoid CWD issues in production
load_dotenv(BASE_DIR / ".env")


def _env_str(name: str, default: str = "") -> str:
    """Read environment values robustly as strings."""
    value = os.getenv(name, default)
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


def _env_bool(name: str, default: str = "False") -> bool:
    return _env_str(name, default).lower() in ('true', '1', 'yes')


def _env_list(name: str, default: str = '') -> list[str]:
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


def _dedupe(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _detect_lan_ip() -> str:
    """Best-effort local LAN IP detection for development settings only."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
            probe.connect(('8.8.8.8', 80))
            return probe.getsockname()[0]
    except OSError:
        return ''


def _development_lan_hosts() -> list[str]:
    configured_hosts = _env_list('DEV_LAN_HOSTS') + _env_list('DEV_LAN_IPS')
    detected_host = _detect_lan_ip()
    if detected_host:
        configured_hosts.append(detected_host)

    return _dedupe([
        host.strip()
        for host in configured_hosts
        if host.strip() and host.strip() not in {'localhost', '127.0.0.1', '0.0.0.0'}
    ])


def _local_dev_origins(hosts: list[str], ports: tuple[int, ...] = (5173, 4173, 3000)) -> list[str]:
    origins: list[str] = []
    for host in hosts:
        for port in ports:
            origins.append(f'http://{host}:{port}')
    return origins


def _env_proxy_ssl_header(name: str = 'SECURE_PROXY_SSL_HEADER') -> tuple[str, str] | None:
    raw_value = _env_str(name, '')
    if not raw_value:
        return None

    parts = [part.strip() for part in raw_value.split(',', 1)]
    if len(parts) != 2 or not parts[0] or not parts[1]:
        raise ImproperlyConfigured(
            f'{name} must be set as "HEADER_NAME,header-value" when provided.'
        )

    return parts[0], parts[1]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ov1io#b(%s+zc#ue30exe(t(sa3d7xf*i4biy7zh*yx95pzitd'
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, explicitly set DEBUG=False via environment variable
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Environment selector used for security-sensitive development overrides.
DJANGO_ENV = _env_str('DJANGO_ENV', 'production').lower()

# Parse ALLOWED_HOSTS from environment variable or use sensible development defaults
_allowed_hosts_str = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
)
DEVELOPMENT_LAN_HOSTS = _development_lan_hosts() if DEBUG and DJANGO_ENV == 'development' else []
ALLOWED_HOSTS = _dedupe(
    [host.strip() for host in _allowed_hosts_str.split(',') if host.strip()]
    + DEVELOPMENT_LAN_HOSTS
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'crops',
    'farm',
    'accounts',
]

# Debug Toolbar nur in Entwicklung aktivieren
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    # Debug Toolbar Middleware nur in Entwicklung aktivieren
    *(['debug_toolbar.middleware.DebugToolbarMiddleware'] if DEBUG else []),
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Debug Toolbar Einstellungen nur in Entwicklung
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite if DB_ENGINE is not set or set to 'sqlite', otherwise use PostgreSQL
db_engine = os.getenv('DB_ENGINE', 'sqlite')

if db_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'ATOMIC_REQUESTS': True,
            # SQLite's default rollback-journal mode takes an exclusive lock on the
            # whole file for a writer's entire transaction, blocking readers too.
            # Django's dev server handles requests in separate threads, so a page
            # firing several concurrent API calls (some of which write) reliably
            # produces "database is locked" under CI/e2e load even with a generous
            # busy timeout, because readers queue up behind the writer instead of
            # proceeding concurrently. WAL mode lets readers proceed while a single
            # writer is active, which is what actually removes the contention; the
            # timeout stays as a backstop for the now-rare case of two writers
            # overlapping.
            #
            # transaction_mode=IMMEDIATE is the second half of the fix: with the
            # default DEFERRED transactions, an ATOMIC_REQUESTS request that reads
            # first and writes later (e.g. login: read user -> write session +
            # last_login) starts on a read snapshot and then cannot upgrade to a
            # write lock if any other writer committed in between - SQLite reports
            # "database is locked" for that upgrade IMMEDIATELY, without consulting
            # the busy timeout, because retrying on a stale snapshot could never
            # succeed. BEGIN IMMEDIATE takes the write lock up front, so concurrent
            # writers queue on the busy timeout instead of failing mid-request.
            # Reproduced locally with concurrent logins + parallel GETs; see the
            # e2e "database is locked" flake history (git log around this block).
            'OPTIONS': {
                'timeout': 20,
                'transaction_mode': 'IMMEDIATE',
                'init_command': (
                    'PRAGMA journal_mode=WAL;'
                    'PRAGMA synchronous=NORMAL;'
                ),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'farmplanner_db'),
            'USER': os.getenv('DB_USER', 'farmplanner'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'farmplanner'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'ATOMIC_REQUESTS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
if DJANGO_ENV == 'development':
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Localhost uses /static/ by default; production can override via DJANGO_STATIC_URL.
STATIC_URL = _env_str('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (user uploads)
# Media files are stored at project root level (next to backend and frontend folders)
# to keep them separate from the application code
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', PROJECT_ROOT / 'media'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend base URL used for links in account emails.
def _normalize_url_prefix(raw_value: str) -> str:
    trimmed = raw_value.strip()
    if not trimmed or trimmed == '/':
        return ''
    return trimmed.strip('/')


URL_PREFIX = _normalize_url_prefix(_env_str('URL_PREFIX', ''))

_frontend_url_from_env = _env_str('FRONTEND_URL', '')
FRONTEND_URL = _frontend_url_from_env or 'http://localhost:5173'
_public_frontend_url_from_env = _env_str('PUBLIC_FRONTEND_URL', '')
PUBLIC_FRONTEND_URL = _public_frontend_url_from_env or FRONTEND_URL

parsed_public_frontend_url = urlparse(PUBLIC_FRONTEND_URL)

if not DEBUG:
    if SECRET_KEY == 'django-insecure-ov1io#b(%s+zc#ue30exe(t(sa3d7xf*i4biy7zh*yx95pzitd':
        raise ImproperlyConfigured('SECRET_KEY must be set explicitly when DEBUG is False.')
    if not parsed_public_frontend_url.scheme or not parsed_public_frontend_url.netloc:
        raise ImproperlyConfigured('PUBLIC_FRONTEND_URL must be an absolute URL when DEBUG is False.')

if (
    DJANGO_ENV not in {'development', 'test'}
    and (parsed_public_frontend_url.hostname or '').lower() in {'localhost', '127.0.0.1', '::1'}
):
    raise ImproperlyConfigured('PUBLIC_FRONTEND_URL must not point to localhost outside local development.')

PROJECT_INVITATION_EXPIRY_DAYS = int(_env_str('PROJECT_INVITATION_EXPIRY_DAYS', '14') or '14')
AGENT_LOGIN_ENABLED = _env_str('AGENT_LOGIN_ENABLED', 'False').lower() in ('true', '1', 'yes')

# Email configuration (console backend by default, override via environment for SMTP or other backends).
EMAIL_BACKEND = _env_str(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = _env_str('EMAIL_HOST', 'mail.uberspace.de')
EMAIL_PORT = int(_env_str('EMAIL_PORT', '587') or '587')
EMAIL_USE_TLS = _env_str('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = _env_str('EMAIL_HOST_USER', 'info@openfarmplanner.org')
EMAIL_HOST_PASSWORD = _env_str('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = _env_str('DEFAULT_FROM_EMAIL', 'OpenFarmPlanner <info@openfarmplanner.org>')
SUPPORT_CONTACT_EMAIL = _env_str('SUPPORT_CONTACT_EMAIL', 'info@openfarmplanner.org')
SERVER_EMAIL = _env_str('SERVER_EMAIL', EMAIL_HOST_USER)

# CORS and CSRF origins are intentionally configured independently via environment variables.
_cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
DEVELOPMENT_LAN_ORIGINS = (
    _local_dev_origins(DEVELOPMENT_LAN_HOSTS)
    if DEBUG and DJANGO_ENV == 'development'
    else []
)
CORS_ALLOWED_ORIGINS = _dedupe(
    [origin.strip() for origin in _cors_origins_str.split(',') if origin.strip()]
    + DEVELOPMENT_LAN_ORIGINS
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-project-id',
]

_csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = _dedupe(
    [origin.strip() for origin in _csrf_origins_str.split(',') if origin.strip()]
    + DEVELOPMENT_LAN_ORIGINS
)

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _env_str('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = _env_str('CSRF_COOKIE_SAMESITE', 'Lax')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', 'True')
    SECURE_PROXY_SSL_HEADER = _env_proxy_ssl_header()
    USE_X_FORWARDED_HOST = _env_bool('USE_X_FORWARDED_HOST', 'False')
    SECURE_HSTS_SECONDS = int(_env_str('SECURE_HSTS_SECONDS', '31536000') or '31536000')
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True')
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', 'True')
    SECURE_REFERRER_POLICY = _env_str('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
    X_FRAME_OPTIONS = _env_str('X_FRAME_OPTIONS', 'DENY')
    SECURE_CONTENT_TYPE_NOSNIFF = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': _env_str('THROTTLE_AUTH_LOGIN', '10/minute'),
        'auth_register': _env_str('THROTTLE_AUTH_REGISTER', '5/minute'),
        'auth_activation': _env_str('THROTTLE_AUTH_ACTIVATION', '10/minute'),
        'auth_resend_activation': _env_str('THROTTLE_AUTH_RESEND_ACTIVATION', '5/minute'),
        'auth_password_reset_request': _env_str('THROTTLE_AUTH_PASSWORD_RESET_REQUEST', '5/minute'),
        'auth_password_reset_confirm': _env_str('THROTTLE_AUTH_PASSWORD_RESET_CONFIRM', '10/minute'),
        'invitation_accept': _env_str('THROTTLE_INVITATION_ACCEPT', '20/hour'),
        'agent_login_consume': _env_str('THROTTLE_AGENT_LOGIN_CONSUME', '30/hour'),
    },
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.OpenFarmPlannerPageNumberPagination',
    'PAGE_SIZE': 100,
}

CSRF_COOKIE_SAMESITE = _env_str('CSRF_COOKIE_SAMESITE', CSRF_COOKIE_SAMESITE)
SESSION_COOKIE_SAMESITE = _env_str('SESSION_COOKIE_SAMESITE', SESSION_COOKIE_SAMESITE)
if DEBUG:
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', 'False')
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', 'False')



E2E_TEST_TOKEN = os.getenv('E2E_TEST_TOKEN', '').strip()
