from django.urls import path

from .views import (
    ActivateView,
    CsrfTokenView,
    LoginView,
    LogoutView,
    MeView,
    AccountDeleteRequestView,
    AccountEmailChangeConfirmView,
    AccountEmailChangeRequestView,
    AccountPasswordChangeView,
    AccountProfileView,
    AccountPublicProfileView,
    AccountRestoreView,
    AccountStatusView,
    ConsentAcceptView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    ResendActivationView,
)

urlpatterns = [
    path('csrf/', CsrfTokenView.as_view(), name='auth-csrf'),
    path('register/', RegisterView.as_view(), name='auth-register'),
    path('activate/', ActivateView.as_view(), name='auth-activate'),
    path('login/', LoginView.as_view(), name='auth-login'),
    path('logout/', LogoutView.as_view(), name='auth-logout'),
    path('me/', MeView.as_view(), name='auth-me'),
    path('consent/accept/', ConsentAcceptView.as_view(), name='auth-consent-accept'),
    path('account/profile/', AccountProfileView.as_view(), name='auth-account-profile'),
    path('account/public-profile/', AccountPublicProfileView.as_view(), name='auth-account-public-profile'),
    path('account/change-email/', AccountEmailChangeRequestView.as_view(), name='auth-account-change-email'),
    path('account/confirm-email-change/', AccountEmailChangeConfirmView.as_view(), name='auth-account-confirm-email-change'),
    path('account/change-password/', AccountPasswordChangeView.as_view(), name='auth-account-change-password'),
    path('account/delete-request/', AccountDeleteRequestView.as_view(), name='auth-account-delete-request'),
    path('account/restore/', AccountRestoreView.as_view(), name='auth-account-restore'),
    path('account/status/', AccountStatusView.as_view(), name='auth-account-status'),
    path('resend-activation/', ResendActivationView.as_view(), name='auth-resend-activation'),
    path('password-reset/', PasswordResetRequestView.as_view(), name='auth-password-reset'),
    path('password-reset-confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
]
