# Generated by Django 5.2.9 on 2025-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='binomial_name',
            field=models.CharField(blank=True, help_text='Scientific binomial name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='common_names',
            field=models.JSONField(blank=True, help_text='Array of common names in different languages', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the crop'),
        ),
        migrations.AddField(
            model_name='culture',
            name='growing_degree_days',
            field=models.IntegerField(blank=True, help_text='Growing degree days requirement', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_labor_min_per_m2',
            field=models.IntegerField(blank=True, help_text='Labor minutes per square meter for harvesting', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='height_cm',
            field=models.IntegerField(blank=True, help_text='Plant height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='hilling_labor_min_per_m2',
            field=models.IntegerField(blank=True, help_text='Labor minutes per square meter for hilling', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='maturity_days',
            field=models.IntegerField(blank=True, help_text='Days to maturity', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='openfarm_id',
            field=models.CharField(blank=True, help_text='OpenFarm internal identifier', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='openfarm_raw',
            field=models.JSONField(blank=True, help_text='Complete raw JSON from OpenFarm (preserves all data)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='openfarm_slug',
            field=models.SlugField(blank=True, help_text='OpenFarm URL-friendly slug', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='plant_spacing_cm',
            field=models.IntegerField(blank=True, help_text='Distance between plants in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='planting_labor_min_per_m2',
            field=models.IntegerField(blank=True, help_text='Labor minutes per square meter for planting', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='row_spacing_cm',
            field=models.IntegerField(blank=True, help_text='Distance between rows in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='sowing_method',
            field=models.CharField(blank=True, help_text='Method of sowing (direct, transplant, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='spread_cm',
            field=models.IntegerField(blank=True, help_text='Plant spread/width in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='sun_requirements',
            field=models.CharField(blank=True, help_text='Sun exposure requirements', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='taxon',
            field=models.CharField(blank=True, help_text='Taxonomic rank (Species, Genus, Family, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='yield_kg_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kilograms per square meter', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='days_to_harvest',
            field=models.IntegerField(blank=True, help_text='Average days from planting to harvest', null=True),
        ),
        migrations.AddIndex(
            model_name='culture',
            index=models.Index(fields=['openfarm_id'], name='farm_cultur_openfar_650be5_idx'),
        ),
        migrations.AddIndex(
            model_name='culture',
            index=models.Index(fields=['name', 'variety'], name='farm_cultur_name_5e8994_idx'),
        ),
    ]
