# Generated by Django 5.2.9 on 2025-12-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='growstuff_id',
            field=models.IntegerField(blank=True, help_text='Growstuff API crop ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='growstuff_slug',
            field=models.CharField(blank=True, help_text='Growstuff API crop slug', max_length=200),
        ),
        migrations.AddField(
            model_name='culture',
            name='last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time synced with Growstuff API', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('growstuff', 'Growstuff API')], default='manual', help_text='Source of the crop data', max_length=20),
        ),
    ]
