# Generated by Django 5.2.9 on 2025-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_culture_growstuff_id_culture_growstuff_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='en_wikipedia_url',
            field=models.URLField(blank=True, help_text='English Wikipedia URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='median_days_to_first_harvest',
            field=models.IntegerField(blank=True, help_text='Median days to first harvest', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='median_days_to_last_harvest',
            field=models.IntegerField(blank=True, help_text='Median days to last harvest', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='median_lifespan',
            field=models.IntegerField(blank=True, help_text='Median lifespan in days', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='perennial',
            field=models.BooleanField(blank=True, help_text='Whether the crop is perennial', null=True),
        ),
    ]
