# Generated by Django 5.2.9 on 2025-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_culture_en_wikipedia_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingplan',
            name='area_usage_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters used by this planting plan', max_digits=10, null=True),
        ),
    ]
