# Generated by Django 5.2.9 on 2025-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_remove_bed_length_m_remove_bed_width_m_bed_area_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='length_m',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='width_m',
        ),
        migrations.AddField(
            model_name='bed',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
