# Generated by Django 5.2.9 on 2026-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_add_harvest_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='median_days_to_first_harvest',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='median_days_to_last_harvest',
        ),
        migrations.AddField(
            model_name='culture',
            name='allow_deviation_delivery_weeks',
            field=models.BooleanField(default=False, help_text='Allow deviating delivery weeks'),
        ),
        migrations.AddField(
            model_name='culture',
            name='crop_family',
            field=models.CharField(blank=True, help_text='Crop family for rotation planning', max_length=200),
        ),
        migrations.AddField(
            model_name='culture',
            name='cultivation_type',
            field=models.CharField(blank=True, choices=[('pre_cultivation', 'Pre-cultivation'), ('direct_sowing', 'Direct Sowing')], help_text='Type of cultivation', max_length=30),
        ),
        migrations.AddField(
            model_name='culture',
            name='display_color',
            field=models.CharField(blank=True, help_text='Display color for cultivation calendar (hex format: #RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='culture',
            name='distance_within_row_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance within row in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='expected_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='germination_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Germination rate percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='growth_duration_days',
            field=models.IntegerField(blank=True, help_text='Growth duration in days (from planting to first harvest)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_duration_days',
            field=models.IntegerField(blank=True, help_text='Harvest duration in days (from first to last harvest)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_method',
            field=models.CharField(blank=True, choices=[('per_plant', 'Per Plant'), ('per_sqm', 'Per m²')], help_text='Harvest method', max_length=20),
        ),
        migrations.AddField(
            model_name='culture',
            name='nutrient_demand',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Nutrient demand level', max_length=20),
        ),
        migrations.AddField(
            model_name='culture',
            name='propagation_duration_days',
            field=models.IntegerField(blank=True, help_text='Propagation duration in days', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='row_spacing_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Row spacing in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='safety_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Safety margin percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='sowing_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sowing depth in cm', max_digits=6, null=True),
        ),
    ]
