# Generated by Django 5.2.9 on 2026-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_add_harvest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='allow_deviation_delivery_weeks',
            field=models.BooleanField(default=False, help_text='Allow deviating delivery weeks'),
        ),
        migrations.AddField(
            model_name='culture',
            name='crop_family',
            field=models.CharField(blank=True, help_text='Crop family for rotation planning', max_length=200),
        ),
        migrations.AddField(
            model_name='culture',
            name='cultivation_type',
            field=models.CharField(blank=True, choices=[('direct_sowing', 'Direct Sowing'), ('transplant', 'Transplant'), ('pre_cultivation', 'Pre-cultivation')], help_text='Type of cultivation', max_length=30),
        ),
        migrations.AddField(
            model_name='culture',
            name='display_color',
            field=models.CharField(blank=True, help_text='Display color for cultivation calendar (hex format: #RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='culture',
            name='distance_within_row_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance within row in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='expected_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='germination_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Germination rate percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='growth_duration_weeks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Growth duration in weeks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_duration_weeks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harvest duration in weeks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_method',
            field=models.CharField(blank=True, choices=[('per_plant', 'Per Plant'), ('per_sqm', 'Per m²'), ('per_bed', 'Per Bed')], help_text='Harvest method', max_length=20),
        ),
        migrations.AddField(
            model_name='culture',
            name='internal_article_number',
            field=models.CharField(blank=True, help_text='Internal article/SKU number', max_length=100),
        ),
        migrations.AddField(
            model_name='culture',
            name='nutrient_demand',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Nutrient demand level', max_length=20),
        ),
        migrations.AddField(
            model_name='culture',
            name='propagation_time_weeks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Propagation time in weeks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='required_yield_per_share_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required yield per share per week', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='row_spacing_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Row spacing in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='safety_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Safety margin percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='sowing_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sowing depth in cm', max_digits=6, null=True),
        ),
    ]
