# Generated by Django 5.2.9 on 2026-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_culture_allow_deviation_delivery_weeks_and_more'),
    ]

    operations = [
        # Remove old week-based fields
        migrations.RemoveField(
            model_name='culture',
            name='growth_duration_weeks',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='harvest_duration_weeks',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='propagation_time_weeks',
        ),
        # Remove fields that are no longer needed
        migrations.RemoveField(
            model_name='culture',
            name='internal_article_number',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='required_yield_per_share_per_week',
        ),
        # Remove old Growstuff fields that were renamed
        migrations.RemoveField(
            model_name='culture',
            name='median_days_to_first_harvest',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='median_days_to_last_harvest',
        ),
        # Add new day-based fields
        migrations.AddField(
            model_name='culture',
            name='growth_duration_days',
            field=models.IntegerField(blank=True, help_text='Growth duration in days (from planting to first harvest)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='harvest_duration_days',
            field=models.IntegerField(blank=True, help_text='Harvest duration in days (from first to last harvest)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='propagation_duration_days',
            field=models.IntegerField(blank=True, help_text='Propagation duration in days', null=True),
        ),
        # Update cultivation_type choices (remove 'transplant', keep only 'pre_cultivation' and 'direct_sowing')
        migrations.AlterField(
            model_name='culture',
            name='cultivation_type',
            field=models.CharField(
                blank=True,
                choices=[('pre_cultivation', 'Pre-cultivation'), ('direct_sowing', 'Direct Sowing')],
                help_text='Type of cultivation',
                max_length=30
            ),
        ),
        # Update harvest_method choices (remove 'per_bed')
        migrations.AlterField(
            model_name='culture',
            name='harvest_method',
            field=models.CharField(
                blank=True,
                choices=[('per_plant', 'Per Plant'), ('per_sqm', 'Per m²')],
                help_text='Harvest method',
                max_length=20
            ),
        ),
    ]
