# Generated by Django 5.2.9 on 2026-01-08 15:42

from django.db import migrations, models
from decimal import Decimal


def convert_cm_to_m(apps, schema_editor):
    """Convert existing spacing data from centimeters to meters.
    
    This migration converts:
    - distance_within_row_cm -> distance_within_row_m (cm / 100)
    - row_spacing_cm -> row_spacing_m (cm / 100)
    - sowing_depth_cm -> sowing_depth_m (cm / 100)
    """
    Culture = apps.get_model('farm', 'Culture')
    
    for culture in Culture.objects.all():
        # Convert distance_within_row from cm to m
        if culture.distance_within_row_cm is not None:
            culture.distance_within_row_m = float(culture.distance_within_row_cm) / 100.0
        
        # Convert row_spacing from cm to m
        if culture.row_spacing_cm is not None:
            culture.row_spacing_m = float(culture.row_spacing_cm) / 100.0
        
        # Convert sowing_depth from cm to m
        if culture.sowing_depth_cm is not None:
            culture.sowing_depth_m = float(culture.sowing_depth_cm) / 100.0
        
        culture.save()


def convert_m_to_cm(apps, schema_editor):
    """Reverse migration: convert meters back to centimeters."""
    Culture = apps.get_model('farm', 'Culture')
    
    for culture in Culture.objects.all():
        # Convert distance_within_row from m to cm
        if culture.distance_within_row_m is not None:
            culture.distance_within_row_cm = Decimal(str(culture.distance_within_row_m * 100.0))
        
        # Convert row_spacing from m to cm
        if culture.row_spacing_m is not None:
            culture.row_spacing_cm = Decimal(str(culture.row_spacing_m * 100.0))
        
        # Convert sowing_depth from m to cm
        if culture.sowing_depth_m is not None:
            culture.sowing_depth_cm = Decimal(str(culture.sowing_depth_m * 100.0))
        
        culture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_culture_refactor_timing_fields'),
    ]

    operations = [
        # Step 1: Add new meter-based fields
        migrations.AddField(
            model_name='culture',
            name='distance_within_row_m',
            field=models.FloatField(blank=True, help_text='Distance within row in meters (stored in SI units)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='row_spacing_m',
            field=models.FloatField(blank=True, help_text='Row spacing in meters (stored in SI units)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='sowing_depth_m',
            field=models.FloatField(blank=True, help_text='Sowing depth in meters (stored in SI units)', null=True),
        ),
        # Step 2: Convert existing data from cm to m
        migrations.RunPython(convert_cm_to_m, convert_m_to_cm),
        # Step 3: Remove old centimeter-based fields
        migrations.RemoveField(
            model_name='culture',
            name='distance_within_row_cm',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='row_spacing_cm',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='sowing_depth_cm',
        ),
    ]
