# Generated by Copilot: Remove days_to_harvest from Culture model
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0010_remove_culture_germination_rate_safety_margin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="culture",
            name="days_to_harvest",
        ),
    ]
