# Generated by Django 5.2.9 on 2026-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_remove_culture_days_to_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='seed_supplier',
            field=models.CharField(blank=True, help_text='Seed supplier/manufacturer', max_length=200),
        ),
    ]
