# Generated by Django 5.2.9 on 2026-01-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_add_seeding_fields_to_culture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='en_wikipedia_url',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='growstuff_id',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='growstuff_slug',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='median_lifespan',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='perennial',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='source',
        ),
    ]
