# Generated by Django 5.2.9 on 2026-02-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_remove_culture_growstuff_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Supplier name', max_length=200)),
                ('name_normalized', models.CharField(editable=False, help_text='Normalized name for deduplication', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='culture',
            name='seed_supplier',
            field=models.CharField(blank=True, help_text='Seed supplier/manufacturer (legacy field)', max_length=200),
        ),
        migrations.AddField(
            model_name='culture',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Seed supplier (preferred over seed_supplier text field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultures', to='farm.supplier'),
        ),
    ]
