# Generated by Django 5.2.9 on 2026-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_add_supplier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='name_normalized',
            field=models.CharField(db_index=True, default='', editable=False, help_text='Normalized name for deduplication', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='culture',
            name='variety_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Normalized variety for deduplication', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='culture',
            constraint=models.UniqueConstraint(fields=('name_normalized', 'variety_normalized', 'supplier'), name='unique_culture_normalized', violation_error_message='A culture with this name, variety, and supplier already exists.'),
        ),
    ]
