# Generated by Django 5.2.9 on 2026-02-06 16:48

from django.db import migrations


def backfill_normalized_fields(apps, schema_editor):
    """Backfill normalized fields for existing Culture records."""
    Culture = apps.get_model('farm', 'Culture')
    
    # Import normalization function inline to avoid issues during migration
    def normalize_text(value):
        if not value:
            return None
        normalized = ' '.join(value.split())
        if not normalized:
            return None
        return normalized.casefold()
    
    # Update each culture with normalized fields
    for culture in Culture.objects.all():
        culture.name_normalized = normalize_text(culture.name) or ''
        culture.variety_normalized = normalize_text(culture.variety)
        culture.save(update_fields=['name_normalized', 'variety_normalized'])


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_add_culture_normalized_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_normalized_fields, migrations.RunPython.noop),
    ]
