# Generated by Django 5.2.9 on 2026-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0017_backfill_culture_normalized_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="package_size_g",
            field=models.FloatField(
                blank=True, help_text="Package size in grams", null=True
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="thousand_kernel_weight_g",
            field=models.FloatField(
                blank=True, help_text="Weight of 1000 kernels in grams", null=True
            ),
        ),
    ]
