# Generated by Django 5.2.9 on 2026-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0019_normalize_seed_rate_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culture",
            name="seed_rate_unit",
            field=models.CharField(
                blank=True,
                help_text="Unit for seed rate (e.g. 'g/m²', 'seeds/m', 'seeds_per_plant')",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="culture",
            name="seed_rate_value",
            field=models.FloatField(
                blank=True,
                help_text="Seed rate value (per m², per meter, or per plant, depending on unit)",
                null=True,
            ),
        ),
    ]
