# Generated by Django 5.2.9 on 2026-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_alter_culture_seed_rate_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='seed_rate_unit',
            field=models.CharField(blank=True, help_text="Unit for seed rate (e.g. 'g/m²', 'seeds/m', 'seeds_per_plant')", max_length=30, null=True),
        ),
    ]
