# Generated by Django 5.2.9 on 2026-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_alter_culture_seed_rate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='variety',
            field=models.CharField(max_length=200),
        ),
    ]
