# Generated by Django 5.2.9 on 2026-02-24 11:01

import django.db.models.deletion
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0022_alter_culture_variety"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to=farm.models.note_attachment_upload_path),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "planting_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="farm.plantingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
