# Generated by Django 5.2.9 on 2026-02-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0023_noteattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_path", models.CharField(max_length=500, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("orphaned_at", models.DateTimeField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CultureRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("changed_fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_name", models.CharField(blank=True, max_length=150)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="farm.culture",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="culture",
            name="image_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Referenced media file for this culture image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cultures",
                to="farm.mediafile",
            ),
        ),
    ]
