# Generated by Django 5.2.9 on 2026-02-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0024_mediafile_culturerevision_culture_image_file"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="culture",
            name="unique_culture_normalized",
        ),
        migrations.AddField(
            model_name="culture",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="culture",
            constraint=models.UniqueConstraint(
                fields=(
                    "name_normalized",
                    "variety_normalized",
                    "supplier",
                    "deleted_at",
                ),
                name="unique_culture_normalized",
                violation_error_message="A culture with this name, variety, and supplier already exists.",
            ),
        ),
    ]
