# Generated by Django 5.2.9 on 2026-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0025_remove_culture_unique_culture_normalized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
