# Generated by Django 5.2.9 on 2026-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0026_projectrevision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="culture",
            name="unique_culture_normalized",
        ),
        migrations.AddConstraint(
            model_name="culture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name_normalized", "variety_normalized", "supplier"),
                name="unique_culture_normalized",
                violation_error_message="A culture with this name, variety, and supplier already exists.",
            ),
        ),
    ]
