# Generated by Django 5.2.9 on 2026-02-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0027_remove_culture_unique_culture_normalized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentAccountingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("reresearch", "Re-research"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("cached_input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("web_search_call_count", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_accounting_runs",
                        to="farm.culture",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
