# Generated by Django 5.2.9 on 2026-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0027_remove_culture_unique_culture_normalized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="expected_yield_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg_per_m2", "kg/m²"),
                    ("kg_per_m", "kg/m"),
                    ("kg_per_plant", "kg/plant"),
                ],
                help_text="Unit for expected yield",
                max_length=20,
            ),
        ),
    ]
