# Generated by Django 5.2.9 on 2026-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_seedpackage_and_drop_legacy_package_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedpackage',
            options={'ordering': ['size_value']},
        ),
        migrations.RemoveConstraint(
            model_name='seedpackage',
            name='unique_seed_package_per_culture_size_unit',
        ),
        migrations.RemoveField(
            model_name='seedpackage',
            name='article_number',
        ),
        migrations.RemoveField(
            model_name='seedpackage',
            name='size_unit',
        ),
        migrations.RemoveField(
            model_name='seedpackage',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='seedpackage',
            name='size_value',
            field=models.DecimalField(decimal_places=3, help_text='Package size in grams', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='seedpackage',
            constraint=models.UniqueConstraint(fields=('culture', 'size_value'), name='unique_seed_package_per_culture_size'),
        ),
    ]
