# Generated by Django 5.2.9 on 2026-03-01 10:05

from django.db import migrations, models


def convert_seed_units_to_grams(apps, schema_editor):
    SeedPackage = apps.get_model('farm', 'SeedPackage')
    SeedPackage.objects.filter(size_unit='seeds').update(size_unit='g')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0029_seedpackage_and_drop_legacy_package_size"),
    ]

    operations = [
        migrations.RunPython(convert_seed_units_to_grams, noop_reverse),
        migrations.AlterField(
            model_name="seedpackage",
            name="size_unit",
            field=models.CharField(
                choices=[("g", "Grams")], default="g", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="seedpackage",
            name="size_value",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
