# Generated by Django 5.2.9 on 2026-03-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0030_alter_seedpackage_size_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seedpackage",
            name="article_number",
        ),
        migrations.RemoveField(
            model_name="seedpackage",
            name="available",
        ),
        migrations.RemoveField(
            model_name="seedpackage",
            name="source_url",
        ),
    ]
