# Generated by Django 5.2.9 on 2026-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0033_fix_supplier_domain_fields_postgres"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="supplier_product_url",
            field=models.URLField(
                blank=True,
                help_text="Supplier product page URL for enrichment",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="homepage_url",
            field=models.URLField(help_text="Supplier homepage URL"),
        ),
    ]
