# Generated by Django 5.2.9 on 2026-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0034_alter_culture_supplier_product_url_and_more'),
        ('farm', '0034_supplier_is_active_and_domain_defaults'),
    ]

    operations = [
    ]
