# Generated by Django 5.2.9 on 2026-03-03 07:18

from django.db import migrations, models


def forwards_fill_cultivation_types(apps, schema_editor):
    Culture = apps.get_model('farm', 'Culture')
    for culture in Culture.objects.all():
        if isinstance(culture.cultivation_types, list) and culture.cultivation_types:
            continue
        if culture.cultivation_type:
            culture.cultivation_types = [culture.cultivation_type]
        else:
            culture.cultivation_types = ['pre_cultivation']
            culture.cultivation_type = 'pre_cultivation'
        culture.save(update_fields=['cultivation_types', 'cultivation_type'])


def backwards_fill_cultivation_type(apps, schema_editor):
    Culture = apps.get_model('farm', 'Culture')
    for culture in Culture.objects.all():
        if isinstance(culture.cultivation_types, list) and culture.cultivation_types:
            culture.cultivation_type = culture.cultivation_types[0]
            culture.save(update_fields=['cultivation_type'])


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0035_merge_20260302_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="cultivation_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="culture",
            name="seed_rate_by_cultivation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="cultivation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pre_cultivation", "Pre-cultivation"),
                    ("direct_sowing", "Direct Sowing"),
                ],
                help_text="Deprecated single cultivation type (kept for compatibility)",
                max_length=30,
            ),
        ),
        migrations.RunPython(forwards_fill_cultivation_types, backwards_fill_cultivation_type),
    ]
