# Generated by Django 5.2.9 on 2026-03-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0039_alter_field_area_sqm_single_decimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
    ]
