# Generated by Django 5.2.9 on 2026-03-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_invitation_fields(apps, schema_editor):
    Invitation = apps.get_model('farm', 'ProjectInvitation')
    for invitation in Invitation.objects.all().iterator():
        normalized_email = (invitation.email or '').strip().lower()
        status = 'pending'
        if invitation.revoked_at is not None:
            status = 'revoked'
        elif invitation.accepted_at is not None:
            status = 'accepted'

        Invitation.objects.filter(id=invitation.id).update(
            email=normalized_email,
            email_normalized=normalized_email,
            status=status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0047_bootstrap_projects_and_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinvitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_invitations_accepted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="email_normalized",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_invitations_revoked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.RunPython(backfill_invitation_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="projectinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("project", "email_normalized"),
                name="unique_open_project_invitation_per_email",
            ),
        ),
    ]
