# Generated by Django 5.2.9 on 2026-03-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0048_projectinvitation_accepted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="is_modified_from_source",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="culture",
            name="origin_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("imported", "Imported")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="source_public_version",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PublicCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published")],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("variety", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("seed_supplier", models.CharField(blank=True, max_length=200)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("version", models.IntegerField(default=1)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name_normalized",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "variety_normalized",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=200
                    ),
                ),
                ("crop_family", models.CharField(blank=True, max_length=200)),
                (
                    "nutrient_demand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cultivation_types", models.JSONField(blank=True, default=list)),
                (
                    "cultivation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pre_cultivation", "Pre-cultivation"),
                            ("direct_sowing", "Direct Sowing"),
                        ],
                        max_length=30,
                    ),
                ),
                ("growth_duration_days", models.IntegerField(blank=True, null=True)),
                ("harvest_duration_days", models.IntegerField(blank=True, null=True)),
                (
                    "propagation_duration_days",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "harvest_method",
                    models.CharField(
                        blank=True,
                        choices=[("per_plant", "Per Plant"), ("per_sqm", "Per m²")],
                        max_length=20,
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("allow_deviation_delivery_weeks", models.BooleanField(default=False)),
                ("distance_within_row_m", models.FloatField(blank=True, null=True)),
                ("row_spacing_m", models.FloatField(blank=True, null=True)),
                ("sowing_depth_m", models.FloatField(blank=True, null=True)),
                ("seed_rate_value", models.FloatField(blank=True, null=True)),
                (
                    "seed_rate_unit",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("seed_rate_by_cultivation", models.JSONField(blank=True, null=True)),
                (
                    "sowing_calculation_safety_percent",
                    models.FloatField(blank=True, null=True),
                ),
                ("thousand_kernel_weight_g", models.FloatField(blank=True, null=True)),
                ("seeding_requirement", models.FloatField(blank=True, null=True)),
                (
                    "seeding_requirement_type",
                    models.CharField(blank=True, max_length=30),
                ),
                ("display_color", models.CharField(blank=True, max_length=7)),
                ("seed_packages", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_cultures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_cultures",
                        to="farm.project",
                    ),
                ),
                (
                    "source_project_culture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_public_cultures",
                        to="farm.culture",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "variety"],
            },
        ),
        migrations.AddField(
            model_name="culture",
            name="source_public_culture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_cultures",
                to="farm.publicculture",
            ),
        ),
    ]
