# Generated by Django 5.2.9 on 2026-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0049_culture_is_modified_from_source_culture_origin_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culture",
            name="origin_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("imported", "Imported")],
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="publicculture",
            name="status",
            field=models.CharField(
                choices=[("published", "Published")], default="published", max_length=50
            ),
        ),
    ]
