# Generated by Django 5.2.9 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


BOOTSTRAP_PROJECT_NAME = 'Gelawi Zwiebelzopf'
BOOTSTRAP_PROJECT_SLUG = 'gelawi-zwiebelzopf'


def backfill_null_projects(apps, schema_editor):
    Project = apps.get_model('farm', 'Project')
    Supplier = apps.get_model('farm', 'Supplier')
    Location = apps.get_model('farm', 'Location')
    Field = apps.get_model('farm', 'Field')
    Bed = apps.get_model('farm', 'Bed')
    BedLayout = apps.get_model('farm', 'BedLayout')
    FieldLayout = apps.get_model('farm', 'FieldLayout')
    Culture = apps.get_model('farm', 'Culture')
    ProjectRevision = apps.get_model('farm', 'ProjectRevision')
    SeedPackage = apps.get_model('farm', 'SeedPackage')
    PlantingPlan = apps.get_model('farm', 'PlantingPlan')
    Task = apps.get_model('farm', 'Task')
    NoteAttachment = apps.get_model('farm', 'NoteAttachment')

    project, _ = Project.objects.get_or_create(
        slug=BOOTSTRAP_PROJECT_SLUG,
        defaults={'name': BOOTSTRAP_PROJECT_NAME, 'description': '', 'is_active': True},
    )

    models_to_update = [
        Supplier,
        Location,
        Field,
        Bed,
        BedLayout,
        FieldLayout,
        Culture,
        ProjectRevision,
        SeedPackage,
        PlantingPlan,
        Task,
        NoteAttachment,
    ]
    for model in models_to_update:
        model.objects.filter(project__isnull=True).update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0050_alter_culture_origin_type_alter_publicculture_status'),
    ]

    operations = [
        migrations.RunPython(backfill_null_projects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bed',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='beds',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='bedlayout',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bed_layouts',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='culture',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cultures',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='field',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fields',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='fieldlayout',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='field_layouts',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locations',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='note_attachments',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='plantingplan',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='planting_plans',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_revisions',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='seedpackage',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='seed_packages',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='suppliers',
                to='farm.project',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='farm.project',
            ),
        ),
    ]
