# Generated by Django 5.2.9 on 2026-03-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0052_agentlogintoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlogintoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
