# Generated by Django 5.2.9 on 2026-04-02 07:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_culture_supplier_data(apps, schema_editor):
    Culture = apps.get_model("farm", "Culture")
    CultureSupplierData = apps.get_model("farm", "CultureSupplierData")
    SeedPackage = apps.get_model("farm", "SeedPackage")

    for culture in Culture.objects.filter(supplier_id__isnull=False).iterator():
        package_rows = SeedPackage.objects.filter(culture_id=culture.id).values("size_value", "size_unit")
        packaging_sizes = [
            {
                "size_value": float(row["size_value"]),
                "size_unit": row["size_unit"],
            }
            for row in package_rows
        ]
        CultureSupplierData.objects.update_or_create(
            culture_id=culture.id,
            supplier_id=culture.supplier_id,
            defaults={
                "project_id": culture.project_id,
                "supplier_name": culture.seed_supplier or "",
                "supplier_product_url": culture.supplier_product_url or "",
                "thousand_kernel_weight_g": culture.thousand_kernel_weight_g,
                "packaging_sizes": packaging_sizes,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0057_alter_culture_method_seed_field_help_texts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureSupplierData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_url", models.URLField(blank=True)),
                ("supplier_product_name", models.CharField(blank=True, max_length=255)),
                ("supplier_product_url", models.URLField(blank=True)),
                ("packaging_sizes", models.JSONField(blank=True, default=list)),
                ("thousand_kernel_weight_g", models.FloatField(blank=True, null=True)),
                ("germination_rate", models.FloatField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_data",
                        to="farm.culture",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_supplier_data",
                        to="farm.project",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_supplier_data",
                        to="farm.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["culture", "supplier"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("culture", "supplier"),
                        name="unique_culture_supplier_data_per_supplier",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_culture_supplier_data, migrations.RunPython.noop),
    ]
