# Generated by Django 5.2.9 on 2026-04-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0061_location_coordinates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["location", "name"],
                "verbose_name": "Parzelle",
                "verbose_name_plural": "Parzellen",
            },
        ),
        migrations.AlterField(
            model_name="bed",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="farm.field",
                verbose_name="Parzelle",
            ),
        ),
    ]
