# Generated by Django 5.2.9 on 2026-04-27 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0065_consolidate_supplier_tkg_to_culture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="plantingplan",
            index=models.Index(
                fields=["project", "-planting_date"],
                name="farm_planti_project_3551cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantingplan",
            index=models.Index(
                fields=["project", "bed", "planting_date", "harvest_end_date"],
                name="farm_planti_project_950fc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantingplan",
            index=models.Index(
                fields=["project", "culture"], name="farm_planti_project_73fcc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectrevision",
            index=models.Index(
                fields=["project", "-created_at"], name="farm_projec_project_e9d31c_idx"
            ),
        ),
    ]
