# Generated by Codex on 2026-05-14

from django.db import migrations, models


def drop_legacy_supplier_unique_constraints(_apps, schema_editor) -> None:
    """Drop PostgreSQL supplier uniqueness constraints left by older migrations."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        ALTER TABLE farm_supplier
            DROP CONSTRAINT IF EXISTS farm_supplier_name_normalized_key,
            DROP CONSTRAINT IF EXISTS farm_supplier_name_481b90a0_uniq;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0066_plantingplan_farm_planti_project_3551cf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="homepage_url",
            field=models.URLField(blank=True, help_text="Supplier homepage URL"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(help_text="Supplier name", max_length=200),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name_normalized",
            field=models.CharField(
                editable=False,
                help_text="Normalized name for deduplication",
                max_length=200,
            ),
        ),
        migrations.RunPython(drop_legacy_supplier_unique_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("project", "name_normalized"),
                name="unique_supplier_name_per_project",
            ),
        ),
    ]
