# Generated by Codex on 2026-06-10

from typing import Any

from django.db import migrations, models
from django.db.models import Count


def build_unique_name(
    model: Any,
    parent_field_name: str,
    parent_id: int,
    base_name: str,
    excluded_ids: list[int],
) -> str:
    """Return a parent-scoped unique name by appending a numeric suffix."""
    existing_names = set(
        model.objects.filter(**{parent_field_name: parent_id})
        .exclude(id__in=excluded_ids)
        .values_list("name", flat=True)
    )
    suffix = 2
    candidate = f"{base_name} ({suffix})"
    while candidate in existing_names:
        suffix += 1
        candidate = f"{base_name} ({suffix})"
    return candidate


def make_field_and_bed_names_unique(apps: Any, schema_editor: Any) -> None:
    """Rename existing duplicates so the following unique constraints can be applied."""
    field_model = apps.get_model("farm", "Field")
    bed_model = apps.get_model("farm", "Bed")

    duplicate_field_groups = (
        field_model.objects.values("location_id", "name")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("location_id", "name")
    )
    for group in duplicate_field_groups:
        fields = list(
            field_model.objects.filter(
                location_id=group["location_id"],
                name=group["name"],
            ).order_by("id")
        )
        for field in fields[1:]:
            field.name = build_unique_name(
                field_model,
                "location_id",
                group["location_id"],
                group["name"],
                [field.id],
            )
            field.save(update_fields=["name"])

    duplicate_bed_groups = (
        bed_model.objects.values("field_id", "name")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("field_id", "name")
    )
    for group in duplicate_bed_groups:
        beds = list(
            bed_model.objects.filter(
                field_id=group["field_id"],
                name=group["name"],
            ).order_by("id")
        )
        for bed in beds[1:]:
            bed.name = build_unique_name(
                bed_model,
                "field_id",
                group["field_id"],
                group["name"],
                [bed.id],
            )
            bed.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0068_project_deleted_at"),
    ]

    operations = [
        migrations.RunPython(make_field_and_bed_names_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("location", "name"),
                name="unique_field_name_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                fields=("field", "name"),
                name="unique_bed_name_per_field",
            ),
        ),
    ]
