# Generated by Django 5.2.9 on 2026-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0069_unique_field_and_bed_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='harvest_method',
            field=models.CharField(blank=True, choices=[('per_plant', 'Per Plant'), ('per_sqm', 'Per m²')], help_text='Yield unit for expected harvest', max_length=20),
        ),
    ]
