# Generated by Django 5.2.9 on 2026-07-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0070_alter_culture_harvest_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField()),
                ('changed_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_revisions', to='farm.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='farm_entity_project_8a1306_idx'), models.Index(fields=['project', 'entity_type', 'object_id', '-created_at'], name='farm_entity_project_fcbc63_idx')],
            },
        ),
    ]
