# Generated by Django 5.2.9 on 2026-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0073_remove_enrichmentaccountingrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='supplier_product_url',
            field=models.URLField(blank=True, help_text='Supplier product page URL', null=True),
        ),
    ]
