# Generated by Django 5.2.9 on 2026-07-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0074_alter_culture_supplier_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingplan',
            name='bed',
            field=models.ForeignKey(blank=True, help_text='Optional until the plan is fully filled in — a plan can be saved as a draft before a bed is chosen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_plans', to='farm.bed'),
        ),
        migrations.AlterField(
            model_name='plantingplan',
            name='planting_date',
            field=models.DateField(blank=True, help_text='Optional until the plan is fully filled in — a plan can be saved as a draft before a date is chosen.', null=True),
        ),
    ]
