# Generated by Django 5.2.9 on 2026-07-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0075_alter_plantingplan_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingplan',
            name='culture',
            field=models.ForeignKey(blank=True, help_text='Optional until the plan is fully filled in — a plan can be saved as a draft before a culture is chosen, as long as a bed is chosen instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_plans', to='farm.culture'),
        ),
    ]
