# Generated by Django 5.2.9 on 2026-07-23 06:24

import django.core.serializers.json
import django.db.models.deletion
import json
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models


PUBLIC_CULTURE_VERSION_SNAPSHOT_FIELDS = [
    'name',
    'variety',
    'notes',
    'crop_species',
    'original_language_code',
    'crop_family',
    'nutrient_demand',
    'cultivation_types',
    'cultivation_type',
    'growth_duration_days',
    'harvest_duration_days',
    'propagation_duration_days',
    'harvest_method',
    'expected_yield',
    'allow_deviation_delivery_weeks',
    'distance_within_row_m',
    'row_spacing_m',
    'sowing_depth_m',
    'seed_rate_value',
    'seed_rate_unit',
    'seed_rate_by_cultivation',
    'sowing_calculation_safety_percent',
    'thousand_kernel_weight_g',
    'seeding_requirement',
    'seeding_requirement_type',
    'display_color',
    'seed_packages',
]


def _json_normalized(value):
    return json.loads(json.dumps(value, cls=DjangoJSONEncoder))


def backfill_public_culture_versions(apps, schema_editor):
    PublicCulture = apps.get_model('farm', 'PublicCulture')
    PublicCultureVersion = apps.get_model('farm', 'PublicCultureVersion')
    for public_culture in PublicCulture.objects.all().iterator():
        snapshot = {}
        for field in PUBLIC_CULTURE_VERSION_SNAPSHOT_FIELDS:
            if field == 'crop_species':
                snapshot[field] = public_culture.crop_species_id
            else:
                snapshot[field] = _json_normalized(getattr(public_culture, field))
        version = PublicCultureVersion.objects.create(
            public_culture=public_culture,
            version_number=max(public_culture.version or 1, 1),
            snapshot=snapshot,
            change_summary=[],
            change_comment='',
            created_by_id=public_culture.created_by_id,
        )
        PublicCultureVersion.objects.filter(pk=version.pk).update(
            created_at=public_culture.published_at or public_culture.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0079_publicculturechangeproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCultureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('change_summary', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('change_comment', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_culture_versions', to=settings.AUTH_USER_MODEL)),
                ('public_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='farm.publicculture')),
            ],
            options={
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('public_culture', 'version_number'), name='unique_public_culture_version_number')],
            },
        ),
        migrations.RunPython(backfill_public_culture_versions, migrations.RunPython.noop),
    ]
